//DEBUG MODE
//#define DEBUG

//Choose SSID
#define AP_ESP8266_SSID

#ifdef AP_ESP8266_SSID
  #define STASSID "ESPap"
  #define STAPSK  "PASSWORD"
#endif

#define IP_ADDRESS 192,168,2,150  //IP address of the AP
#define SUBNET 192,168,2,1
#define GATEWAY 255,255,255,0
#define PORT_SERVER 80
#define LED_ONBOARD D4


//RPM_GAUGE
#define PIN_D7_BACKPLANE_RPM D7
#define PIN_D6_FRONTPLANE_RPM D6
#define QUANTITY_LED_BACKPLANE_RPM  4
#define QUANTITY_LED_FRONTPLANE_RPM 13

//SPEED_GAUGE
#define PIN_D5_FRONTPLANE_SPEED D5
#define PIN_D8_BACKPLANE_SPEED D8
#define QUANTITY_LED_BACKPLANE_SPEED 5
#define QUANTITY_LED_FRONTPLANE_SPEED 18

//DISPLAY
#define PIN_D1_DISPLAY D1
#define QUANTITY_LED_DISPLAY 9

//Brightness gauge
#define BRIGHTNESS_FRONTPLANE 60 //75
#define BRIGHTNESS_BACKPLANE 60  //75
#define BRIGHTNESS_DISPLAY 60   //75

//Speed on Led Gauge
#define TIME_WAITING 80

#define NON_COLOR 0
#define RED_COLOR 255
#define GREEN_COLOR 255
#define BLUE_COLOR 255

#define ORANGE_COLOR_FIRST 49
#define ORANGE_COLOR_SECOND 229
#define ORANGE_COLOR_THIRD 36

#define FUNNY_COLOR_FIRST 150
#define FUNNY_COLOR_SECOND 90
#define FUNNY_COLOR_THIRD 200
